name=input() 
age=int(input()) 
cgpa=float(input())
grade=input() 
marks="{:.2f}".format(int(cgpa*100)/100)
print("Name:", name)
print("Age:", age)
print("CGPA:", marks)
print("Grade:", grade)